#!/usr/bin/env python3
"""
Evidence Engine - Deterministic Bug Evidence and Reproduction.

Enriches findings generated by the bug detector (and analyzed by Gemini)
with detailed, structured evidence and reproduction steps.
"""

import json


class EvidenceEngine:
    def __init__(self, crawl_result):
        self.crawl_result = crawl_result

    def enrich(self, report_data):
        """
        Enrich QA findings with deterministic evidence.
        Operates on the findings in place and returns the modified result.
        """
        candidates = report_data.get('root_cause_candidates', [])
        
        for candidate in candidates:
            raw_evidence = candidate.get('evidence', {})
            finding_type = candidate.get('type', '')

            # 1. Structure the evidence
            structured_evidence = self._build_structured_evidence(
                finding_type, raw_evidence, candidate
            )
            candidate['evidence_structured'] = structured_evidence

            # 2. Build reproduction steps
            reproduction = self._build_reproduction(finding_type, candidate, structured_evidence)
            candidate['reproduction'] = reproduction

            # 3. Ensure expected and actual results exist
            expected = candidate.get('expected_result')
            actual = candidate.get('actual_result')

            if not expected or expected == "Not specified.":
                candidate['expected_result'] = self._generate_expected_result(finding_type, candidate)

            if not actual or actual == "Not specified.":
                candidate['actual_result'] = self._generate_actual_result(finding_type, candidate, structured_evidence)

        return report_data

    def _build_structured_evidence(self, finding_type, raw_evidence, candidate):
        """Format the raw evidence into a standardized structure based on finding type."""
        evidence = {
            "screenshot": self._get_best_screenshot(candidate),
            "responsive": None,
            "http_error": None,
            "console_errors": [],
            "network_failures": []
        }

        http_errors = raw_evidence.get('http_errors', [])
        if http_errors:
            first_err = http_errors[0]
            evidence['http_error'] = {
                "request": {
                    "url": first_err.get('url'),
                    "method": first_err.get('method', 'GET'),
                    "status": first_err.get('status'),
                    "resource_type": first_err.get('resource_type', 'unknown')
                },
                "affected_pages": candidate.get('affected_pages', []),
                "occurrences": candidate.get('occurrences', len(http_errors))
            }

        console_errors = raw_evidence.get('console_errors', [])
        if console_errors:
            first_err = console_errors[0]
            evidence['console_errors'].append({
                "message": first_err.get('text', ''),
                "page": first_err.get('page', ''),
                "occurrences": candidate.get('occurrences', len(console_errors)),
                "related_request": None  # Could be correlated if needed
            })

        network_failures = raw_evidence.get('network_failures', [])
        if network_failures:
            first_fail = network_failures[0]
            evidence['network_failures'].append({
                "url": first_fail.get('url'),
                "method": first_fail.get('method'),
                "failure": first_fail.get('failure'),
                "occurrences": candidate.get('occurrences', len(network_failures))
            })

        responsive_checks = raw_evidence.get('responsive_checks', {})
        if responsive_checks:
            devices = candidate.get('affected_devices')
            device = devices[0] if devices else 'Unknown'
            # Default viewport if not explicitly captured by crawler
            viewport = {"width": 1280, "height": 720}
            if 'iphone' in device.lower():
                viewport = {"width": 390, "height": 844}
            elif 'ipad' in device.lower():
                viewport = {"width": 810, "height": 1080}
            
            evidence['responsive'] = {
                "device": device,
                "viewport": viewport,
                "overflow": {}
            }
            
            if responsive_checks.get('horizontal_overflow'):
                evidence['responsive']['overflow'] = {
                    "amount": responsive_checks.get('overflow_pixels', 0)
                }
            
            if responsive_checks.get('forms_outside_viewport', 0) > 0:
                evidence['responsive']['element'] = {
                    "type": "form",
                    "count": responsive_checks.get('forms_outside_viewport')
                }
            elif responsive_checks.get('clipped_buttons', 0) > 0:
                evidence['responsive']['element'] = {
                    "type": "button",
                    "count": responsive_checks.get('clipped_buttons')
                }

        return evidence

    def _get_best_screenshot(self, candidate):
        """Get the most relevant screenshot for a candidate."""
        screenshots = candidate.get('screenshots', [])
        if screenshots:
            return screenshots[0]
        
        page_screenshots = candidate.get('page_screenshots', [])
        if page_screenshots:
            return page_screenshots[0].get('screenshot')
            
        return None

    def _build_reproduction(self, finding_type, candidate, evidence):
        """Build deterministic reproduction steps."""
        url = candidate.get('url')
        if not url:
            pages = candidate.get('affected_pages')
            url = pages[0] if pages else ''
            
        devices = candidate.get('affected_devices')
        device = devices[0] if devices else None
        viewport = None

        steps = []
        if finding_type == 'responsive_issue' and evidence.get('responsive'):
            viewport = evidence['responsive']['viewport']
            steps.extend([
                f"Open {url}",
                f"Set viewport to {device} ({viewport['width']}x{viewport['height']})",
                "Scroll to the affected section",
                "Observe the affected element extending beyond the viewport boundary"
            ])
        elif finding_type == 'http_error':
            req = (evidence.get('http_error') or {}).get('request', {})
            steps.extend([
                f"Open {url}",
                "Open browser developer tools",
                "Open the Network tab",
                "Reload the page",
                f"Locate the failed request to {req.get('url')}",
                f"Observe HTTP {req.get('status')} response"
            ])
        elif finding_type == 'console_error':
            steps.extend([
                f"Open {url}",
                "Open browser developer tools",
                "Open the Console tab",
                "Reload the page",
                "Observe the JavaScript/runtime error in the console"
            ])
        elif finding_type == 'network_failure':
            fail = evidence.get('network_failures', [{}])[0]
            steps.extend([
                f"Open {url}",
                "Open browser developer tools",
                "Open the Network tab",
                "Reload the page",
                f"Observe the failed request to {fail.get('url')} resulting in {fail.get('failure')}"
            ])
        else:
            steps.extend([
                f"Open {url}",
                "Follow the scenario to reproduce the issue."
            ])

        return {
            "url": url,
            "device": device,
            "viewport": viewport,
            "steps": steps,
            "evidence_available": any([evidence['screenshot'], evidence['responsive'], evidence['http_error'], evidence['console_errors'], evidence['network_failures']])
        }

    def _generate_expected_result(self, finding_type, candidate):
        """Generate a deterministic expected result."""
        if finding_type == 'http_error':
            return "The application endpoints and resources should respond with a successful status code."
        elif finding_type == 'console_error':
            return "The page should load without triggering unhandled exceptions or JavaScript errors."
        elif finding_type == 'network_failure':
            return "All required page resources and API requests should complete successfully."
        elif finding_type == 'responsive_issue':
            return "All visible content should remain within the device viewport without horizontal overflow."
        return "The application should function correctly without errors."

    def _generate_actual_result(self, finding_type, candidate, evidence):
        """Generate a deterministic actual result."""
        if finding_type == 'http_error' and evidence.get('http_error'):
            req = evidence['http_error']['request']
            return f"The page triggered a {req.get('status')} response from {req.get('url')}."
        elif finding_type == 'console_error' and evidence.get('console_errors'):
            return f"A console error was triggered: {evidence['console_errors'][0]['message']}."
        elif finding_type == 'network_failure' and evidence.get('network_failures'):
            fail = evidence['network_failures'][0]
            return f"A request to {fail.get('url')} failed with {fail.get('failure')}."
        elif finding_type == 'responsive_issue' and evidence.get('responsive'):
            overflow = evidence['responsive'].get('overflow', {}).get('amount')
            if overflow:
                return f"An element extends {overflow}px beyond the right viewport boundary."
            return "Elements were clipped outside the viewport bounds."
        return candidate.get('description', 'An unexpected error occurred.')

    @staticmethod
    def run(qa_findings_path, crawl_file_path):
        """Main entry point to enrich a file."""
        import os
        
        if not os.path.exists(qa_findings_path):
            print(f"ERROR: QA findings not found at {qa_findings_path}")
            return None
            
        with open(qa_findings_path, 'r', encoding='utf-8') as f:
            qa_findings = json.load(f)
            
        crawl_result = {}
        if crawl_file_path and os.path.exists(crawl_file_path):
            with open(crawl_file_path, 'r', encoding='utf-8') as f:
                crawl_result = json.load(f)
                
        engine = EvidenceEngine(crawl_result)
        enriched_result = engine.enrich(qa_findings)
        
        # We write it back to the same file to keep the pipeline flow simple
        with open(qa_findings_path, 'w', encoding='utf-8') as f:
            json.dump(enriched_result, f, indent=2, ensure_ascii=False)
            
        return qa_findings_path

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("report", help="Path to gemini_qa_report.json")
    parser.add_argument("--crawl", help="Path to crawl result JSON")
    args = parser.parse_args()
    
    EvidenceEngine.run(args.report, args.crawl)
